name: Publish on NPM

on:
  release:
    types: [created]

jobs:
  build-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build-publish
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
